export class CustomPizza {
  'name': string;
  'dough': [
    {
      'name': string,
      'add': boolean,
      'price': number,
      'id': string,
    },
    {
      'name': string,
      'add': boolean,
      'price': number,
      'id': string,
    },
    {'name': string,
      'add': boolean,
      'price': number,
      'id': string,
    }
  ];
  'sauce': [
    {
      'name': string,
      'add': boolean,
      'price': number,
      'id': string,
    },
    {
      'name': string,
      'add': boolean,
      'price': number,
      'id': string,
    },
    {'name': string,
      'add': boolean,
      'price': number,
      'id': string,
    }
  ];
  'cheese': [
    {'name': string,
      'add': boolean,
      'price': number,
      'id': string,
    },
    {
      'name': string,
      'add': boolean,
      'price': number,
      'id': string,
    },
    {'name': string,
      'add': boolean,
      'price': number,
      'id': string,
    },
    {'name': string,
      'add': boolean,
      'price': number,
      'id': string,
    },
    {'name': string,
      'add': boolean,
      'price': number,
      'id': string,
    },
    {'name': string,
      'add': boolean,
      'price': number,
      'id': string,
    },
    {'name': string,
      'add': boolean,
      'price': number,
      'id': string,
    },
    {'name': string,
      'add': boolean,
      'price': number,
      'id': string,
    }
  ];
  'meat': [
    {'name': string,
      'add': boolean,
      'price': number,
      'id': string,

    },
    {'name': string,
      'add': boolean,
      'price': number,
      'id': string,

    },
    {'name': string,
      'add': boolean,
      'price': number,
      'id': string,
    },
    {'name': string,
      'add': boolean,
      'price': number,
      'id': string,
    },
    {'name': string,
      'add': boolean,
      'price': number,
      'id': string,
    },
    {'name': string,
      'add': boolean,
      'price': number,
      'id': string,
    },
    {'name': string,
      'add': boolean,
      'price': number,
      'id': string,
    },
    {'name': string,
      'add': boolean,
      'price': number,
      'id': string,
    },
    {'name': string,
      'add': boolean,
      'price': number,
      'id': string,
    },
    {'name': string,
      'add': boolean,
      'price': number,
      'id': string,
    }
  ];
  'vegetables': [
    {'name': string,
      'add': boolean,
      'price': number,
      'id': string,
    },
    {'name': string,
      'add': boolean,
      'price': number,
      'id': string,
    },
    {'name': string,
      'add': boolean,
      'price': number,
      'id': string,
    },
    {'name': string,
      'add': boolean,
      'price': number,
      'id': string,
    },
    {'name': string,
      'add': boolean,
      'price': number,
      'id': string,
    },
    {'name': string,
      'add': boolean,
      'price': number,
      'id': string,
    },
    {'name': string,
      'add': boolean,
      'price': number,
      'id': string,
    },
    {'name': string,
      'add': boolean,
      'price': number,
      'id': string,
    },
    {'name': string,
      'add': boolean,
      'price': number,
      'id': string,
    },
    {'name': string,
      'add': boolean,
      'price': number,
      'id': string,
    },
    {'name': string,
      'add': boolean,
      'price': number,
      'id': string,
       },
    {'name': string,
      'add': boolean,
      'price': number,
      'id': string,
       }
  ];
}
